12: Hall.csv: none: {'count': 1700, 'truepos': 92, 'falseneg': 11, 'unknownyes': 3, 'falsepos': 74, 'unique': 1700}
12: Hall.csv: three: {'count': 1150, 'truepos': 102, 'falseneg': 0, 'unknownyes': 4, 'falsepos': 4, 'unique': 550}
12: Hall.csv: machine: {'count': 601, 'truepos': 99, 'falseneg': 2, 'unknownyes': 5, 'falsepos': 3, 'unique': 430}
12: Wahono.csv: none: {'count': 2760, 'truepos': 56, 'falseneg': 5, 'unknownyes': 1, 'falsepos': 134, 'unique': 2760}
12: Wahono.csv: three: {'count': 2939, 'truepos': 57, 'falseneg': 2, 'unknownyes': 3, 'falsepos': 13, 'unique': 1400}
12: Wahono.csv: machine: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2d2-11>
Subject: Job 244075: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 12> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 12> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2d2-11>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Thu Oct 12 08:46:58 2017
Results reported at Thu Oct 12 10:17:15 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 12
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :   6375.65 sec.
    Max Memory :       169 MB
    Max Swap   :      1187 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/12.err.244075> for stderr output of this job.

