26: Hall.csv: none: {'count': 2190, 'truepos': 90, 'falseneg': 14, 'unknownyes': 2, 'falsepos': 186, 'unique': 2190}
26: Hall.csv: three: {'count': 1462, 'truepos': 100, 'falseneg': 2, 'unknownyes': 4, 'falsepos': 9, 'unique': 680}
26: Hall.csv: machine: {'count': 820, 'truepos': 97, 'falseneg': 5, 'unknownyes': 4, 'falsepos': 24, 'unique': 610}
26: Wahono.csv: none: {'count': 2310, 'truepos': 51, 'falseneg': 7, 'unknownyes': 4, 'falsepos': 200, 'unique': 2310}
26: Wahono.csv: three: {'count': 3114, 'truepos': 58, 'falseneg': 0, 'unknownyes': 4, 'falsepos': 33, 'unique': 1410}
26: Wahono.csv: machine: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2d2-9>
Subject: Job 213967: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 26> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 26> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2d2-9>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Mon Oct  9 14:05:23 2017
Results reported at Mon Oct  9 15:56:47 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 26
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :   8009.37 sec.
    Max Memory :       171 MB
    Max Swap   :      1190 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/26.err.213967> for stderr output of this job.

