4: Hall.csv: none: {'count': 1770, 'truepos': 70, 'falseneg': 33, 'correction': 0, 'unknownyes': 1, 'falsepos': 6, 'unique': 1770}
4: Hall.csv: three: {'count': 1490, 'truepos': 77, 'falseneg': 25, 'correction': 46, 'unknownyes': 2, 'falsepos': 0, 'unique': 720}
4: Hall.csv: machine: {'count': 1716, 'truepos': 91, 'falseneg': 12, 'correction': 23, 'unknownyes': 1, 'falsepos': 0, 'unique': 1230}
4: Hall.csv: knee: {'count': 712, 'truepos': 84, 'falseneg': 16, 'correction': 22, 'unknownyes': 4, 'falsepos': 0, 'unique': 500}
4: Wahono.csv: none: {'count': 1950, 'truepos': 40, 'falseneg': 20, 'correction': 0, 'unknownyes': 2, 'falsepos': 5, 'unique': 1950}
4: Wahono.csv: three: {'count': 3495, 'truepos': 46, 'falseneg': 13, 'correction': 30, 'unknownyes': 3, 'falsepos': 0, 'unique': 1730}
4: Wahono.csv: machine: {'count': 1732, 'truepos': 52, 'falseneg': 8, 'correction': 20, 'unknownyes': 2, 'falsepos': 1, 'unique': 1240}
4: Wahono.csv: knee: {'count': 863, 'truepos': 45, 'falseneg': 9, 'correction': 8, 'unknownyes': 8, 'falsepos': 0, 'unique': 620}
4: Danijel.csv: none: {'count': 810, 'truepos': 42, 'falseneg': 4, 'correction': 0, 'unknownyes': 2, 'falsepos': 0, 'unique': 810}
4: Danijel.csv: three: {'count': 3402, 'truepos': 35, 'falseneg': 12, 'correction': 17, 'unknownyes': 1, 'falsepos': 0, 'unique': 1690}
4: Danijel.csv: machine: {'count': 1699, 'truepos': 36, 'falseneg': 10, 'correction': 14, 'unknownyes': 2, 'falsepos': 0, 'unique': 1210}
4: Danijel.csv: knee: {'count': 853, 'truepos': 34, 'falseneg': 8, 'correction': 9, 'unknownyes': 6, 'falsepos': 1, 'unique': 620}
4: K_all3.csv: none: {'count': 670, 'truepos': 28, 'falseneg': 14, 'correction': 0, 'unknownyes': 3, 'falsepos': 9, 'unique': 670}
4: K_all3.csv: three: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2b1-1>
Subject: Job 759935: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 4> in cluster <henry2> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 4> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2> at Sat Feb 24 20:13:28 2018.
Job was executed on host(s) <2*n2b1-1>, in queue <single_chassis>, as user <zyu9> in cluster <henry2> at Sat Feb 24 20:13:31 2018.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Sat Feb 24 20:13:31 2018.
Terminated at Sun Feb 25 09:11:12 2018.
Results reported at Sun Feb 25 09:11:12 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 4
------------------------------------------------------------

TERM_OWNER: job killed by owner.
Exited with exit code 1.

Resource usage summary:

    CPU time :                                   47916.20 sec.
    Max Memory :                                 516.86 MB
    Average Memory :                             378.21 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   1561 MB
    Max Processes :                              3
    Max Threads :                                8
    Run time :                                   46675 sec.
    Turnaround time :                            46664 sec.

The output (if any) is above this job summary.



PS: The stderr output (if any) follows:

Traceback (most recent call last):
  File "runner.py", line 352, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "runner.py", line 288, in error_hpcc
    result = BM25(file,queries[file],'est','three')
  File "runner.py", line 206, in BM25
    a,b,c,d =read.train(weighting=True,pne=True)
  File "/home/zyu9/projects/MAR_HPC/Error/src/mar.py", line 584, in train
    self.est_num, self.est = self.estimate_curve(clf, reuse=False, num_neg=len(sample)-len(left))
  File "/home/zyu9/projects/MAR_HPC/Error/src/mar.py", line 395, in estimate_curve
    es.fit(prob[all], y[all])
KeyboardInterrupt


PS:

Fail to open stderr file ./err/4.err.759935: No such file or directory.
The stderr output is included in this report.

